name: bundle

on:
  push:
    branches:
      - master
    paths-ignore:
      - dist/**
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: JesseTG/rm@v1.0.3
        with:
          path: dist
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with: { version: 10 }
      - run: pnpm i
      - run: pnpm build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Bundle'
      - id: autotag
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
      - if: ${{ steps.autotag.outputs.tag != '0.0.0' }}
        run: git push --delete origin ${{ steps.autotag.outputs.tag }}

  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: https://gitgud.io/lolodesu/lolocard.git
          username: StageDog
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
